import mongoose from "mongoose";
import {z} from "zod";
import {connectDB} from "@/lib/db";
import {requireAdmin} from "@/lib/api/require-admin";
import {apiError,apiSuccess} from "@/lib/api/response";
import {ADMIN_RESOURCES} from "@/lib/content/admin-config";
import Location from "@/models/Location";
export const runtime="nodejs";export const dynamic="force-dynamic";
const contentSchema=z.object({title:z.string().trim().min(2).max(180),slug:z.string().trim().toLowerCase().min(1).max(200).regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/),summary:z.string().trim().max(500).optional().default(""),body:z.string().trim().max(50000).optional().default(""),status:z.enum(["draft","published","archived"]).optional().default("draft"),location:z.string().regex(/^[a-f\d]{24}$/i).nullable().optional().default(null),coverImage:z.object({url:z.string().trim().max(2048).optional().default(""),publicId:z.string().trim().max(300).optional().default(""),alt:z.string().trim().max(200).optional().default("")}).strict().optional().default({}),event:z.object({startsAt:z.string().datetime().nullable().optional(),endsAt:z.string().datetime().nullable().optional(),venue:z.string().trim().max(240).optional(),registrationUrl:z.string().trim().max(2048).optional()}).strict().optional(),seo:z.object({title:z.string().trim().max(70).optional(),description:z.string().trim().max(170).optional(),noIndex:z.boolean().optional(),canonicalUrl:z.string().trim().max(2048).optional()}).strict().optional()}).strict();
const submissionSchema=z.object({status:z.enum(["pending","reviewing","approved","rejected"]),adminNotes:z.string().trim().max(3000).optional().default("")}).strict();
const mediaSchema=z.object({url:z.string().url().max(2048).refine(v=>/^https?:\/\//i.test(v)),publicId:z.string().min(1).max(300),folder:z.string().min(1).max(200),alt:z.string().max(200).optional().default(""),caption:z.string().max(500).optional().default(""),mimeType:z.string().max(100).optional().default("image"),bytes:z.number().int().min(0).max(5242880).optional().default(0),width:z.number().int().min(0).nullable().optional(),height:z.number().int().min(0).nullable().optional()}).strict();
const settingsSchema=z.object({siteName:z.string().trim().min(1).max(120),siteUrl:z.string().trim().max(2048).refine(v=>!v||/^https?:\/\//i.test(v)),defaultTitle:z.string().trim().max(70),titleTemplate:z.string().trim().max(120),defaultDescription:z.string().trim().max(170),defaultImage:z.string().trim().max(2048),robotsIndex:z.boolean(),sitemapEnabled:z.boolean(),organizationName:z.string().trim().max(120),organizationLogo:z.string().trim().max(2048)}).strict();
const templateSchema=z.object({entityType:z.enum(["business","category","location","place","guide","event"]),titleTemplate:z.string().trim().max(160),descriptionTemplate:z.string().trim().max(300),canonicalTemplate:z.string().trim().max(300),noIndexByDefault:z.boolean()}).strict();
async function getType(ctx){return (await ctx.params).type;}
async function authorize(){const a=await requireAdmin();return a.response?{response:a.response}:{user:a.user};}
function fail(e){if(e?.code===11000)return apiError("A record with this slug or identifier already exists.",409);if(["ValidationError","CastError","StrictModeError"].includes(e?.name))return apiError("The submitted data is invalid.",400);console.error("[ADMIN CONTENT]",e?.message||e);return apiError("Unable to process this request.",500);}
async function parseBody(request){if((request.headers.get("content-type")||"").split(";")[0].trim().toLowerCase()!=="application/json")return {error:apiError("Content-Type must be application/json.",415)};const body=await request.json().catch(()=>null);if(!body||typeof body!=="object"||Array.isArray(body))return {error:apiError("Invalid JSON body.",400)};return {body};}
export async function GET(request,ctx){const a=await authorize();if(a.response)return a.response;const type=await getType(ctx),r=ADMIN_RESOURCES[type];if(!r)return apiError("Unknown resource.",404);try{await connectDB();const u=new URL(request.url),page=Math.max(1,Number(u.searchParams.get("page"))||1),limit=Math.min(100,Math.max(1,Number(u.searchParams.get("limit"))||50));if(type==="seo"){const item=await r.model.findOne({key:"global"}).lean().exec();return apiSuccess({items:item?[item]:[],total:item?1:0,page,limit});}const filter=r.kind?{kind:r.kind}:{};const status=u.searchParams.get("status");if(r.kind&&["draft","published","archived"].includes(status))filter.status=status;if(type==="submissions"&&["pending","reviewing","approved","rejected"].includes(status))filter.status=status;const [items,total]=await Promise.all([r.model.find(filter).sort({createdAt:-1,_id:-1}).skip((page-1)*limit).limit(limit).lean().exec(),r.model.countDocuments(filter)]);return apiSuccess({items,total,page,limit});}catch(e){return fail(e);}}
export async function POST(request,ctx){const a=await authorize();if(a.response)return a.response;const type=await getType(ctx),r=ADMIN_RESOURCES[type];if(!r)return apiError("Unknown resource.",404);if(type==="submissions")return apiError("Submissions are created through the public endpoint.",405);const parsedBody=await parseBody(request);if(parsedBody.error)return parsedBody.error;const body=parsedBody.body;try{await connectDB();let data;if(r.kind){const p=contentSchema.safeParse(body);if(!p.success)return apiError("Content data is invalid.",400,p.error.issues);data=p.data;if(data.status==="published"&&(!data.summary.trim()||!data.body.trim()))return apiError("Published content requires a summary and body.",400);if(data.location){if(!await Location.exists({_id:data.location,status:"active"}))return apiError("Select an active location.",400);}Object.assign(data,{kind:r.kind,createdBy:a.user.id,updatedBy:a.user.id,publishedAt:data.status==="published"?new Date():null});}else if(type==="media"){const p=mediaSchema.safeParse(body);if(!p.success)return apiError("Media data is invalid.",400,p.error.issues);data={...p.data,uploadedBy:a.user.id};}else if(type==="seo"){const p=settingsSchema.safeParse(body);if(!p.success)return apiError("SEO settings are invalid.",400,p.error.issues);const item=await r.model.findOneAndUpdate({key:"global"},{$set:{...p.data,key:"global",updatedBy:a.user.id}},{new:true,upsert:true,runValidators:true,setDefaultsOnInsert:true}).lean().exec();return apiSuccess({item});}else if(type==="seo-templates"){const p=templateSchema.safeParse(body);if(!p.success)return apiError("SEO template is invalid.",400,p.error.issues);data={...p.data,updatedBy:a.user.id};}else return apiError("Creation is not supported for this resource.",405);const item=await r.model.create(data);return apiSuccess({item},201);}catch(e){return fail(e);}}
export async function PATCH(request,ctx){const a=await authorize();if(a.response)return a.response;const type=await getType(ctx),r=ADMIN_RESOURCES[type];if(!r)return apiError("Unknown resource.",404);const parsedBody=await parseBody(request);if(parsedBody.error)return parsedBody.error;const {body}=parsedBody;try{await connectDB();if(type==="seo"){const p=settingsSchema.partial().strict().safeParse(body.data||{});if(!p.success)return apiError("SEO settings are invalid.",400,p.error.issues);const item=await r.model.findOneAndUpdate({key:"global"},{$set:{...p.data,key:"global",updatedBy:a.user.id}},{new:true,upsert:true,runValidators:true,setDefaultsOnInsert:true}).lean().exec();return apiSuccess({item});}if(!body.id||!mongoose.isValidObjectId(body.id))return apiError("A valid record ID is required.",400);let updates;if(r.kind){const p=contentSchema.partial().strict().safeParse(body.data);if(!p.success)return apiError("Content data is invalid.",400,p.error.issues);updates={...p.data,updatedBy:a.user.id};if(updates.status==="published"){const current=await r.model.findOne({_id:body.id,kind:r.kind}).lean().exec();if(!current)return apiError("Record not found.",404);if(!(updates.body??current.body)?.trim()||!(updates.summary??current.summary)?.trim())return apiError("Published content requires a summary and body.",400);updates.publishedAt=current.publishedAt||new Date();}else if(updates.status)updates.publishedAt=null;}else if(type==="submissions"){const p=submissionSchema.safeParse(body.data);if(!p.success)return apiError("Submission update is invalid.",400,p.error.issues);updates={...p.data,reviewedBy:a.user.id,reviewedAt:new Date()};}else if(type==="media"){const p=mediaSchema.partial().strict().safeParse(body.data);if(!p.success)return apiError("Media update is invalid.",400,p.error.issues);updates=p.data;}else if(type==="seo-templates"){const p=templateSchema.partial().strict().safeParse(body.data);if(!p.success)return apiError("SEO template is invalid.",400,p.error.issues);updates={...p.data,updatedBy:a.user.id};}else return apiError("This resource cannot be updated.",405);const filter=r.kind?{_id:body.id,kind:r.kind}:{_id:body.id};const item=await r.model.findOneAndUpdate(filter,{$set:updates},{new:true,runValidators:true}).lean().exec();if(!item)return apiError("Record not found.",404);return apiSuccess({item});}catch(e){return fail(e);}}
export async function DELETE(request,ctx){const a=await authorize();if(a.response)return a.response;const type=await getType(ctx),r=ADMIN_RESOURCES[type];if(!r)return apiError("Unknown resource.",404);if(!["media","places","guides","events","seo-templates"].includes(type))return apiError("Deletion is not allowed for this resource.",405);const id=new URL(request.url).searchParams.get("id");if(!id||!mongoose.isValidObjectId(id))return apiError("A valid record ID is required.",400);try{await connectDB();const filter=r.kind?{_id:id,kind:r.kind}:{_id:id};const result=await r.model.deleteOne(filter).exec();if(!result.deletedCount)return apiError("Record not found.",404);return apiSuccess({deleted:true});}catch(e){return fail(e);}}
